### ISSUE TITLE
Icon Light Switch defined wrong as Fan

### ISSUE THREAD

**Issue by dwightstanley** [pradeepmouli/isy-js#3]
Change Icon Relay Switch v.39 to a LIGHT from an error listing of FAN in isydevicetypes.js

{
"type": "2.22.57.0",
"address": "",
"name": "(28763B) Icon Relay Switch v39",
"deviceType": "Light",
"connectionType": "Insteon Wired",
"batteryOperated": false

**Comment by dwightstanley** [comment]
Any chance of getting this change made!?
My older ICON light switches show up as Fans in Homekit

**Comment by pradeepmouli** [comment]
Try the latest update (isy-nodejs is the package on npm). This should be fixed.
